on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

name: Test Indie Wiki Buddy Bot
jobs:
  test-bot:
    name: test-bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --ignore-scripts
      - run: bun run test
